### ISSUE TITLE
bin_path is not a function

### ISSUE THREAD

**Issue by mozrat** [mikhail-angelov/mongo-unit#1]
hello,

I'm using mongo-unit happily in my development environment and can execute unit tests against my in-memory database.

However - the same unit tests fail in my CI environment with the following error:

```
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: bin_path is not a function
    1) "before all" hook
```

I've done some reading and found this in [another logged issue.](https://github.com/Mockgoose/Mockgoose/issues/9)

It seems to be a bug in a particular version of mongodb-prebuilt. I wanted to ask you whether mongo-unit will work against a newer version of mongodb-prebuilt to avoid this error?

Thanks

**Comment by mikhail-angelov** [comment]
Hi,
It's good to know, someone uses my package

about this issue
I'm not sure if I update mongo-prebuild - will fix your issue
it's better to find the real root cause of it
I saw this issue before - it may happen if mongo was not started (e.g. port was unavailable, or something else)

BTW if you use Travis CI agents - it should work.

Best Regards
Mikhail

**Comment by mozrat** [comment]
I did see that I was issue number 1!!! It's a great package, thank you for it.
the issue in mongodb-prebuild is that the code is written as

[Line 164 of index.js](https://github.com/winfinit/mongodb-prebuilt/blob/94205c8e1fc806a4436b694425ef224356e8e81f/index.js#L164)

```
var bin_path = bin_path(version);
```

So it's stamping over the bin_path variable by declaring it again. I don't know why my CI runner is taking that path through the code and avoids it on my local machine.

I'm using Gitlab rather than Jenkins.

**Comment by mikhail-angelov** [comment]
maybe if you enable logs in this lib, it helps to understand root cause of problem

on other hand you can clone this repo, increment mongodb-prebuild version and
use this new repo in your application package.json, and check will it work fine with CI or not
if it will work fine, please make a pull request

**Comment by charleskoehl** [comment]
Looks like a great tool to use for testing parse server and cloud code; however, the travis-ci build failed when running "npm test:" on Sept 9:

https://travis-ci.org/mikhail-angelov/mongo-unit/jobs/274967396

**Comment by mikhail-angelov** [comment]
thank you @charleskoehl it's fixed

**Comment by mikhail-angelov** [comment]
@mozrat I've updated mongodb-prebuild version, you are right it's more stable
